### ISSUE TITLE
Doesn't work with Seneca

### ISSUE THREAD

**Issue by mcdonnelldean** [mcollina/tentacoli#2]
BUG :D

(really a note for me)

**Comment by mcollina** [comment]
example? :)

**Comment by mcdonnelldean** [comment]
It's missing a transport :D

**Comment by mcdonnelldean** [comment]
Joking aside this is for me to build a transport. Assign to me if you need. I'll give this a day or two before the end of the month.

**Comment by mcdonnelldean** [comment]
Closing as testing :D

**Comment by mcollina** [comment]
So, do we have a transport?
Il giorno mer 10 feb 2016 alle 23:23 Dean McDonnell <
notifications@github.com> ha scritto:
